version = 0.1

[default.deploy.parameters]
stack_name = "aws-inventory"
resolve_s3 = true
s3_prefix = "aws-inventory"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
